#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any


START = "<!-- codex-agent-orchestration:start -->"
END = "<!-- codex-agent-orchestration:end -->"
GENERATED = "# Generated by $codex-agent-orchestration. Safe to regenerate."


@dataclass(frozen=True)
class ProjectProfile:
    root: Path
    slug: str
    display_name: str
    signals: tuple[str, ...]
    roles: tuple[str, ...]


@dataclass(frozen=True)
class RoleSpec:
    sandbox: str
    model: str
    effort: str
    job_slug: str
    job_title: str
    focus: str


ROLE_SPECS = {
    "architect": RoleSpec(
        "read-only",
        "gpt-5.6",
        "high",
        "plan_mapper",
        "plan mapper",
        "requirements, repository mapping, risks, and implementation sequencing",
    ),
    "backend": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "api_service_builder",
        "API and service builder",
        "APIs, services, server-side logic, jobs, and persistence boundaries",
    ),
    "frontend": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "ui_flow_builder",
        "UI flow builder",
        "UI, client state, accessibility, loading/error states, and browser-facing integrations",
    ),
    "database": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "data_modeler",
        "data modeler",
        "schema, migrations, queries, indexes, and data integrity",
    ),
    "mobile": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "mobile_flow_builder",
        "mobile flow builder",
        "mobile app flows, native integrations, and device-specific validation",
    ),
    "ai": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "model_integration_builder",
        "model integration builder",
        "LLM, agent, retrieval, prompt, evaluation, and model-integration work",
    ),
    "builder": RoleSpec(
        "workspace-write",
        "gpt-5.6",
        "high",
        "feature_builder",
        "feature builder",
        "general implementation work after an approved plan exists",
    ),
    "infra": RoleSpec(
        "workspace-write",
        "gpt-5.6-terra",
        "high",
        "delivery_pipeline_builder",
        "delivery pipeline builder",
        "deployment, CI, containers, infrastructure, observability, and rollback",
    ),
    "tester": RoleSpec(
        "workspace-write",
        "gpt-5.6-terra",
        "high",
        "regression_checker",
        "regression checker",
        "validation, regression tests, edge cases, and coverage gaps",
    ),
    "security": RoleSpec(
        "read-only",
        "gpt-5.6",
        "xhigh",
        "risk_boundary_reviewer",
        "risk boundary reviewer",
        "auth, permissions, secrets, untrusted input, data exposure, payments, and deployment risk",
    ),
    "reviewer": RoleSpec(
        "read-only",
        "gpt-5.6",
        "xhigh",
        "quality_gate_reviewer",
        "quality gate reviewer",
        "correctness, architecture, maintainability, regressions, and missing tests",
    ),
    "judge": RoleSpec(
        "read-only",
        "gpt-5.6",
        "xhigh",
        "release_decision_coordinator",
        "release decision coordinator",
        "cross-agent synthesis, release blocking decisions, and fix-loop routing",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate project-scoped Codex custom agents.")
    parser.add_argument("--project", default=".", help="Target repository root.")
    parser.add_argument("--dry-run", action="store_true", help="Print the generated plan without writing files.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated agent files.")
    parser.add_argument(
        "--generic-names",
        action="store_true",
        help="Use role_job names like architect_plan_mapper instead of project-prefixed names.",
    )
    args = parser.parse_args()

    root = Path(args.project).expanduser().resolve()
    if not root.is_dir():
        raise SystemExit(f"project directory does not exist: {root}")

    profile = profile_project(root)
    agents = build_agents(profile, prefixed=not args.generic_names)
    config = config_toml()
    agents_md = agents_markdown(profile, agents)
    plan = {
        "project": str(root),
        "slug": profile.slug,
        "signals": profile.signals,
        "roles": list(agents),
        "files": [".codex/config.toml", *[f".codex/agents/{name}.toml" for name in agents], "AGENTS.md"],
    }

    if args.dry_run:
        print(json.dumps(plan, indent=2))
        return 0

    codex_dir = root / ".codex"
    agent_dir = codex_dir / "agents"
    agent_dir.mkdir(parents=True, exist_ok=True)
    ensure_config(codex_dir / "config.toml", config)
    for file_name, content in agents.items():
        path = agent_dir / f"{file_name}.toml"
        if path.exists() and GENERATED not in path.read_text(encoding="utf-8") and not args.force:
            print(f"skip existing hand-written agent: {path}", file=sys.stderr)
            continue
        path.write_text(content, encoding="utf-8")
        tomllib.loads(content)
    upsert_agents_md(root / "AGENTS.md", agents_md)
    print(json.dumps(plan, indent=2))
    return 0


def profile_project(root: Path) -> ProjectProfile:
    display_name = project_name(root)
    slug = slugify(display_name or root.name)
    signals = set[str]()
    files = {path.name for path in root.iterdir() if path.is_file()}
    all_paths = [path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_file() and skip_path(path, root)]

    package = read_package(root / "package.json")
    dependencies = package.get("dependencies", {})
    dev_dependencies = package.get("devDependencies", {})
    dependency_names = set(dependencies if isinstance(dependencies, dict) else {})
    dependency_names |= set(dev_dependencies if isinstance(dev_dependencies, dict) else {})
    deps = " ".join(sorted(dependency_names)).lower()
    if "package.json" in files or any(path.endswith((".ts", ".tsx", ".js", ".jsx")) for path in all_paths):
        signals.add("javascript")
    if any(token in deps for token in ("react", "next", "vue", "svelte", "vite", "angular")) or any(
        path.endswith((".tsx", ".jsx")) for path in all_paths
    ):
        signals.add("frontend")
    if any(token in deps for token in ("express", "fastify", "nestjs", "koa", "hono")):
        signals.add("backend")
    if "pyproject.toml" in files or "requirements.txt" in files or any(path.endswith(".py") for path in all_paths):
        signals.add("python")
        signals.add("backend")
    if any(part in all_paths for part in ("Dockerfile", "docker-compose.yml")) or any(
        path.startswith((".github/workflows/", "terraform/", "infra/", "k8s/", "helm/")) for path in all_paths
    ):
        signals.add("infra")
    if any(path.startswith(("migrations/", "prisma/", "supabase/", "alembic/")) for path in all_paths):
        signals.add("database")
    if any(path.startswith(("ios/", "android/")) for path in all_paths) or "react-native" in deps or "expo" in deps:
        signals.add("mobile")
    if any(token in deps for token in ("openai", "langchain", "llamaindex", "ai-sdk")) or any(
        token in " ".join(all_paths).lower() for token in ("rag", "llm", "embedding", "agent")
    ):
        signals.add("ai")
    if any(path.endswith((".md", ".mdx", ".rst")) for path in all_paths):
        signals.add("docs")
    if any(token in " ".join(all_paths).lower() for token in ("auth", "permission", "secret", "payment", "stripe", "security")):
        signals.add("security")

    roles = ["architect"]
    if "backend" in signals:
        roles.append("backend")
    if "frontend" in signals:
        roles.append("frontend")
    if "database" in signals:
        roles.append("database")
    if "mobile" in signals:
        roles.append("mobile")
    if "ai" in signals:
        roles.append("ai")
    if not any(role in roles for role in ("backend", "frontend", "database", "mobile", "ai")):
        roles.append("builder")
    if "infra" in signals:
        roles.append("infra")
    roles.append("tester")
    if "security" in signals:
        roles.append("security")
    roles.append("reviewer")
    if len(roles) >= 7:
        roles.append("judge")

    return ProjectProfile(root, slug, display_name, tuple(sorted(signals)), tuple(dict.fromkeys(roles)))


def build_agents(profile: ProjectProfile, *, prefixed: bool) -> dict[str, str]:
    result: dict[str, str] = {}
    for role in profile.roles:
        name = agent_name(profile, role, prefixed=prefixed)
        result[name] = agent_toml(profile, role, name)
    return result


def agent_name(profile: ProjectProfile, role: str, *, prefixed: bool) -> str:
    spec = ROLE_SPECS[role]
    parts = [role, spec.job_slug]
    if prefixed:
        parts.insert(0, profile.slug)
    return "_".join(parts).replace("-", "_")


def agent_toml(profile: ProjectProfile, role: str, name: str) -> str:
    spec = ROLE_SPECS[role]
    instructions = instructions_for(role, profile)
    return f'''{GENERATED}
name = "{name}"
description = "{profile.display_name} {role} agent ({spec.job_title}) for {spec.focus}."
model = "{spec.model}"
model_reasoning_effort = "{spec.effort}"
sandbox_mode = "{spec.sandbox}"

developer_instructions = """
{instructions}
"""
'''


def instructions_for(role: str, profile: ProjectProfile) -> str:
    spec = ROLE_SPECS[role]
    common = (
        f"You are the {profile.display_name} {role} specialist for the job: {spec.job_title}.\n"
        "Follow existing repository conventions and keep work bounded to the parent task.\n"
        "Do not commit, push, publish, deploy, rotate secrets, or change access controls.\n"
    )
    by_role = {
        "architect": "Inspect before planning. Map modules, risks, tests, and a safe agent split. Do not modify files.",
        "backend": "Implement only backend-scoped changes from the approved plan. Run relevant tests and report changed files.",
        "frontend": "Implement only frontend-scoped changes from the approved plan. Check states, accessibility basics, and visual regressions.",
        "database": "Implement schema or data-layer changes carefully. Preserve migrations and identify rollback or data integrity risks.",
        "mobile": "Implement mobile-scoped changes and call out platform-specific test limits.",
        "ai": "Implement AI/agent/model integration work with explicit prompt, evaluation, token, privacy, and failure-mode notes.",
        "builder": "Implement the smallest defensible change from the approved plan. Avoid unrelated refactors.",
        "infra": "Handle CI, deployment, containers, infrastructure, observability, and rollback planning. Avoid production side effects.",
        "tester": "Run the smallest meaningful checks first. Add focused tests only when asked. Report commands, failures, and gaps.",
        "security": "Review source to sink. Report actionable exploitability, severity, affected files, and remediation. Do not modify files.",
        "reviewer": "Review like an owner. Lead with correctness, regression, security, and missing-test findings by severity. Do not modify files.",
        "judge": "Synthesize agent results. Decide pass or fix-loop routing based on blocking issues, evidence, and user acceptance criteria.",
    }
    return common + by_role[role]


def agents_markdown(profile: ProjectProfile, agents: dict[str, str]) -> str:
    names = list(agents)
    architect = find_agent_for_role(names, "architect")
    tester = find_agent_for_role(names, "tester")
    reviewer = find_agent_for_role(names, "reviewer")
    implementers = [
        name for name in names
        if name not in {architect, tester, reviewer}
        and not has_agent_role(name, "security")
        and not has_agent_role(name, "judge")
    ]
    security = next((name for name in names if has_agent_role(name, "security")), None)
    judge = next((name for name in names if has_agent_role(name, "judge")), None)
    lines = [
        START,
        "# Codex Agent Orchestration",
        "",
        f"This project uses a generated Codex subagent team for {profile.display_name}.",
        f"Detected signals: {', '.join(profile.signals) or 'general software project'}.",
        "",
        "Default workflow:",
        "",
        f"1. Spawn `{architect}` first for read-only mapping and sequencing.",
        f"2. Delegate implementation to {', '.join(f'`{name}`' for name in implementers)} when their scopes do not overlap.",
        f"3. Run `{tester}` for validation and coverage gaps.",
    ]
    if security:
        lines.append(f"4. Run `{security}` for security-sensitive boundaries.")
        lines.append(f"5. Run `{reviewer}` for final read-only review.")
    else:
        lines.append(f"4. Run `{reviewer}` for final read-only review.")
    if judge:
        lines.append(f"6. Use `{judge}` to reconcile conflicting subagent results and route fix loops.")
    lines.extend([
        "",
        "The parent session owns requirements, approvals, structured outputs, conflict resolution, and final synthesis.",
        "Avoid concurrent write-capable agents editing the same files.",
        END,
        "",
    ])
    return "\n".join(lines)


def find_agent_for_role(names: list[str], role: str) -> str:
    return next(name for name in names if has_agent_role(name, role))


def has_agent_role(name: str, role: str) -> bool:
    role_job_suffix = f"{role}_{ROLE_SPECS[role].job_slug}"
    return name == role or name == role_job_suffix or name.endswith(f"_{role_job_suffix}")


def ensure_config(path: Path, config: str) -> None:
    if not path.exists():
        path.write_text(config, encoding="utf-8")
        return
    text = path.read_text(encoding="utf-8")
    if "[agents]" not in text:
        path.write_text(text.rstrip() + "\n\n" + config, encoding="utf-8")


def upsert_agents_md(path: Path, section: str) -> None:
    if not path.exists():
        path.write_text(section, encoding="utf-8")
        return
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)
    if pattern.search(text):
        updated = pattern.sub(section, text)
    else:
        updated = text.rstrip() + "\n\n" + section
    path.write_text(updated, encoding="utf-8")


def config_toml() -> str:
    return """[agents]
enabled = true
max_concurrent_threads_per_session = 8
default_subagent_model = "gpt-5.6-terra"
default_subagent_reasoning_effort = "medium"
"""


def project_name(root: Path) -> str:
    package = read_package(root / "package.json")
    if isinstance(package.get("name"), str) and package["name"].strip():
        return str(package["name"]).split("/")[-1]
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        try:
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
            name = data.get("project", {}).get("name")
            if isinstance(name, str) and name.strip():
                return name
        except tomllib.TOMLDecodeError:
            pass
    return root.name


def read_package(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    if not slug:
        return "project"
    if slug[0].isdigit():
        slug = f"project_{slug}"
    return slug[:40]


def skip_path(path: Path, root: Path) -> bool:
    rel = path.relative_to(root).parts
    return not any(part in {".git", ".venv", "node_modules", "dist", "build", "__pycache__"} for part in rel)


if __name__ == "__main__":
    raise SystemExit(main())
